name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: List files after build
        run: ls -la
        
      - name: Upload Release Assets
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            manifest.json
            main.js
            styles.css
            
      - name: Create Release
        uses: obsidianmd/obsidian-releases@v1
        with:
          manifest: manifest.json
          main: main.js
          styles: styles.css
          token: ${{ secrets.GITHUB_TOKEN }}
